#python Test1.py --test_n 0
#python Test1.py --test_n 1
#python Test1.py --test_n 2
#python Test1.py --test_n 3
python Test1.py --test_n 4
python Test1.py --test_n 5
python Test1.py --test_n 6
python Test1.py --test_n 7
python Test1.py --test_n 8
python Test1.py --test_n 9
python Test1.py --test_n 10